### ISSUE TITLE
How can we use your method when the user do not want to change anything attribute on his face

### ISSUE THREAD

**Issue by lizi123321123** [fahadshamshad/Clip2Protect#1]
hello! Your paper is very interesting. But I have some question about application scenario. When user do not want to change anything attribute about his face, how your method can work to protect privacy. I very hope that I can get chance to communicate with you.

**Comment by fahadshamshad** [comment]
Hello, if you do not wish to alter facial attributes, you can set the weightage of the clip loss to 0. This ensures no changes are made while still offering protection. However, it might generate minor visual distortions or artifacts.
