### ISSUE TITLE
Identity preserving latent codes

### ISSUE THREAD

**Issue by zhang-lie** [fahadshamshad/Clip2Protect#2]
Your work is awesome. I have one question, in the paper it is mentioned that the optimization is over some identity preserving latent codes but from the code below it seems that requires_grad=True for all these latent codes and all are going in the optimizer. so are all getting updated?

https://github.com/fahadshamshad/Clip2Protect/blob/8596a82cd04a1c85ecc6a805daa2d2710d85de96/adversarial_optimization.py#L215C18-L215C18

**Comment by fahadshamshad** [comment]
Thanks. Despite all latent codes set to requires_grad=True, only identity-preserving ones are updated. This is enforced [here](https://github.com/fahadshamshad/Clip2Protect/blob/8596a82cd04a1c85ecc6a805daa2d2710d85de96/adversarial_optimization.py#L240).
