### ISSUE TITLE
Maybe a bug in your code

### ISSUE THREAD

**Issue by RAgNarokBear** [fahadshamshad/Clip2Protect#5]
I found a bug in your code.
In pivot_tuning.py, line 79, it is supposed to be self.noise_save.append(noise_), instead of self.noise_save.append(noises), which leads to continuously increasing cuda usage.

**Comment by fahadshamshad** [comment]
Thanks for your observation regarding the CUDA and CPU conversion in our code. While we developed and tested on an A100 GPU with 40 GB memory and didn't encounter memory-related challenges, we understand the potential implications of this in different setups like GPU with less memory. We'll make the necessary adjustments. Thank you for bringing this to our attention.
