### ISSUE TITLE
experiment problem

### ISSUE THREAD

**Issue by vegetable-coder11** [fahadshamshad/Clip2Protect#7]
I appreciate your sharing work.However, I'm facing some challenges with the generated results when I directly input the command "python main.py --data_dir input_images --latent_path latents.pt --protected_face_dir results". The generated images do not have satisfactory visual quality. I am specifically interested in performing makeup transfer. Could you please provide guidance on how to resolve this issue?"

**Comment by vegetable-coder11** [comment]
![9488 jpg_wh300](https://github.com/fahadshamshad/Clip2Protect/assets/92798697/ebf9428e-5991-4c19-b9b5-9e6ee540a4e6)
![0_00049](https://github.com/fahadshamshad/Clip2Protect/assets/92798697/ed9f76ae-29da-477b-b1ac-5fc5f61c2770)

**Comment by fahadshamshad** [comment]
To perform only makeup transfer without the adversarial component, you can set the weightage of the adversarial loss to 0. The proposed approach is designed to work with aligned face images. This is a limitation inherent to StyleGAN. From the image you've attached, it seems that it hasn't been aligned using StyleGAN's preprocessing. Please ensure that you preprocess your images using StyleGAN preprocessing.
